### ISSUE TITLE
node-usb installation failure on Ubuntu and Mac

### ISSUE THREAD

**Issue by pathikrit** [schakko/node-usb#13]
I added node-usb as a dependency in a project of mine's package.json but I have spent the past day trying to get it build (using npm install) and nothing works on my mac/linux machine. 

I am trying to install node-usb on my machines (I have a Mac 10.7 and a Ubuntu 12.04). I installed libusb in Ubuntu by using 'sudo apt-get install libusb-1.0-0-dev' and in Mac by doing 'brew install libusb'  (the website recommends me to use the latest libusb but I can't figure out how to install it without homebrew) and I am getting the following error when I do an npm install for my project in Ubuntu:

```
npm http GET https://registry.npmjs.org/node-usb
npm http 304 https://registry.npmjs.org/node-usb

> node-usb@0.0.1 install /home/pathikrit/Projects/ASD/node_modules/node-usb
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : ok /usr/share/nodejs 
Checking for node prefix                 : ok /usr 
Checking for libusb-1.0                  : yes 
Checking for library usb-1.0             : yes 
'configure' finished successfully (0.093s)
Waf: Entering directory `/home/pathikrit/Projects/ASD/node_modules/node-usb/build'
[1/3] cxx: src/node_usb.cc -> build/Release/src/node_usb_1.o
[2/3] cxx: src/bindings.cc -> build/Release/src/bindings_1.o
In file included from ../src/./bindings.h:4:0,
                 from ../src/node_usb.cc:1:
../src/./node_usb.h:15:25: fatal error: node_events.h: No such file or directory
compilation terminated.
In file included from ../src/./bindings.h:4:0,
                 from ../src/bindings.cc:1:
../src/./node_usb.h:15:25: fatal error: node_events.h: No such file or directory
compilation terminated.
Waf: Leaving directory `/home/pathikrit/Projects/ASD/node_modules/node-usb/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx node_usb.cc -> node_usb_1.o}
 -> task failed (err #1): 
    {task: cxx bindings.cc -> bindings_1.o}

npm ERR! node-usb@0.0.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the node-usb@0.0.1 install script.
npm ERR! This is most likely a problem with the node-usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-usb
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.0-24-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pathikrit/Projects/ASD
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message node-usb@0.0.1 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pathikrit/Projects/ASD/npm-debug.log
npm not ok
```

In my Mac, I get this:

```
npm http GET https://registry.npmjs.org/node-usb
npm http 304 https://registry.npmjs.org/node-usb

> node-usb@0.0.1 install /Users/pathikrit/Projects/ASD/node_modules/node-usb
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.18 
Checking for libusb-1.0                  : yes 
Checking for library usb-1.0             : yes 
'configure' finished successfully (0.100s)
Waf: Entering directory `/Users/pathikrit/Projects/ASD/node_modules/node-usb/build'
[1/3] cxx: src/node_usb.cc -> build/Release/src/node_usb_1.o
[2/3] cxx: src/bindings.cc -> build/Release/src/bindings_1.o
In file included from ../src/./bindings.h:4In file included from ../src/./bindings.h:4,
                 from ../src/bindings.cc:1,
                 from ../src/node_usb.cc:1:
:
../src/./node_usb.h:4:20:../src/./node_usb.h:4:20:  error: error: libusb.h: No such file or directorylibusb.h: No such file or directory

../src/./node_usb.h:15:25: error: node_events.h: No such file or directory
../src/./node_usb.h:15:25: error: node_events.h: No such file or directory
In file included from ../src/bindings.cc:1:
../src/./bindings.h:12: error: expected class-name before ‘{’ token
../src/./bindings.h:22: error: ISO C++ forbids declaration of ‘libusb_device’ with no type
../src/./bindings.h:22: error: expected ‘;’ before ‘*’ token
../src/./bindings.h:35: error: expected class-name before ‘{’ token
../src/./bindings.h:40: error: expected `)' before ‘*’ token
../src/./bindings.h:48: error: field ‘device_descriptor’ has incomplete type
../src/bindings.cc: In function ‘v8::Local<v8::Value> NodeUsb::errno_exception(int)’:
../src/bindings.cc:30: error: ‘LIBUSB_ERROR_IO’ was not declared in this scope
../src/bindings.cc:33: error: ‘LIBUSB_ERROR_INVALID_PARAM’ was not declared in this scope
../src/bindings.cc:36: error: ‘LIBUSB_ERROR_ACCESS’ was not declared in this scope
../src/bindings.cc:39: error: ‘LIBUSB_ERROR_NO_DEVICE’ was not declared in this scope
../src/bindings.cc:42: error: ‘LIBUSB_ERROR_NOT_FOUND’ was not declared in this scope
../src/bindings.cc:45: error: ‘LIBUSB_ERROR_BUSY’ was not declared in this scope
../src/bindings.cc:48: error: ‘LIBUSB_ERROR_TIMEOUT’ was not declared in this scope
../src/bindings.cc:51: error: ‘LIBUSB_ERROR_OVERFLOW’ was not declared in this scope
../src/bindings.cc:54: error: ‘LIBUSB_ERROR_PIPE’ was not declared in this scope
../src/bindings.cc:57: error: ‘LIBUSB_ERROR_INTERRUPTED’ was not declared in this scope
../src/bindings.cc:60: error: ‘LIBUSB_ERROR_NO_MEM’ was not declared in this scope
../src/bindings.cc:63: error: ‘LIBUSB_ERROR_NOT_SUPPORTED’ was not declared in this scope
../src/bindings.cc: In static member function ‘static void NodeUsb::Usb::InitalizeUsb(v8::Handle<v8::Object>)’:
../src/bindings.cc:86: error: ‘EventEmitter’ has not been declared
../src/bindings.cc:94: error: ‘LIBUSB_CLASS_PER_INTERFACE’ was not declared in this scope
../src/bindings.cc:95: error: ‘LIBUSB_CLASS_AUDIO’ was not declared in this scope
../src/bindings.cc:96: error: ‘LIBUSB_CLASS_COMM’ was not declared in this scope
../src/bindings.cc:97: error: ‘LIBUSB_CLASS_HID’ was not declared in this scope
../src/bindings.cc:98: error: ‘LIBUSB_CLASS_PRINTER’ was not declared in this scope
../src/bindings.cc:99: error: ‘LIBUSB_CLASS_PTP’ was not declared in this scope
../src/bindings.cc:100: error: ‘LIBUSB_CLASS_MASS_STORAGE’ was not declared in this scope
../src/bindings.cc:101: error: ‘LIBUSB_CLASS_HUB’ was not declared in this scope
../src/bindings.cc:102: error: ‘LIBUSB_CLASS_DATA’ was not declared in this scope
../src/bindings.cc:106: error: ‘LIBUSB_CLASS_VENDOR_SPEC’ was not declared in this scope
../src/bindings.cc:108: error: ‘LIBUSB_DT_DEVICE’ was not declared in this scope
../src/bindings.cc:109: error: ‘LIBUSB_DT_CONFIG’ was not declared in this scope
../src/bindings.cc:110: error: ‘LIBUSB_DT_STRING’ was not declared in this scope
../src/bindings.cc:111: error: ‘LIBUSB_DT_INTERFACE’ was not declared in this scope
../src/bindings.cc:112: error: ‘LIBUSB_DT_ENDPOINT’ was not declared in this scope
../src/bindings.cc:113: error: ‘LIBUSB_DT_HID’ was not declared in this scope
../src/bindings.cc:114: error: ‘LIBUSB_DT_REPORT’ was not declared in this scope
../src/bindings.cc:115: error: ‘LIBUSB_DT_PHYSICAL’ was not declared in this scope
../src/bindings.cc:116: error: ‘LIBUSB_DT_HUB’ was not declared in this scope
../src/bindings.cc:118: error: ‘LIBUSB_ENDPOINT_IN’ was not declared in this scope
../src/bindings.cc:119: error: ‘LIBUSB_ENDPOINT_OUT’ was not declared in this scope
../src/bindings.cc:121: error: ‘LIBUSB_TRANSFER_TYPE_CONTROL’ was not declared in this scope
../src/bindings.cc:122: error: ‘LIBUSB_TRANSFER_TYPE_ISOCHRONOUS’ was not declared in this scope
../src/bindings.cc:123: error: ‘LIBUSB_TRANSFER_TYPE_BULK’ was not declared in this scope
../src/bindings.cc:124: error: ‘LIBUSB_TRANSFER_TYPE_INTERRUPT’ was not declared in this scope
../src/bindings.cc:126: error: ‘LIBUSB_ISO_SYNC_TYPE_NONE’ was not declared in this scope
../src/bindings.cc:127: error: ‘LIBUSB_ISO_SYNC_TYPE_ASYNC’ was not declared in this scope
../src/bindings.cc:128: error: ‘LIBUSB_ISO_SYNC_TYPE_ADAPTIVE’ was not declared in this scope
../src/bindings.cc:129: error: ‘LIBUSB_ISO_SYNC_TYPE_SYNC’ was not declared in this scope
../src/bindings.cc:131: error: ‘LIBUSB_ISO_USAGE_TYPE_DATA’ was not declared in this scope
../src/bindings.cc:132: error: ‘LIBUSB_ISO_USAGE_TYPE_FEEDBACK’ was not declared in this scope
../src/bindings.cc:133: error: ‘LIBUSB_ISO_USAGE_TYPE_IMPLICIT’ was not declared in this scope
../src/bindings.cc: In constructor ‘NodeUsb::Usb::Usb()’:
../src/bindings.cc:149: error: class ‘NodeUsb::Usb’ does not have any field named ‘EventEmitter’
../src/bindings.cc:151: error: ‘devices’ was not declared in this scope
../src/bindings.cc: In destructor ‘NodeUsb::Usb::~Usb()’:
../src/bindings.cc:155: error: ‘devices’ was not declared in this scope
../src/bindings.cc:156: error: ‘libusb_free_device_list’ was not declared in this scope
../src/bindings.cc:159: error: ‘libusb_exit’ was not declared in this scope
../src/bindings.cc: In member function ‘int NodeUsb::Usb::InitalizeLibusb()’:
../src/bindings.cc:169: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc:172: error: ‘libusb_init’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Usb::New(const v8::Arguments&)’:
../src/bindings.cc:206: error: ‘class NodeUsb::Usb’ has no member named ‘Wrap’
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Usb::Refresh(const v8::Arguments&)’:
../src/bindings.cc:218: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Usb::GetDeviceList(const v8::Arguments&)’:
../src/bindings.cc:230: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc:240: error: ‘class NodeUsb::Usb’ has no member named ‘devices’
../src/bindings.cc:241: error: ‘class NodeUsb::Usb’ has no member named ‘devices’
../src/bindings.cc:241: error: ‘libusb_get_device_list’ was not declared in this scope
../src/bindings.cc:242: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc:250: error: ‘class NodeUsb::Usb’ has no member named ‘devices’
../src/bindings.cc: At global scope:
../src/bindings.cc:318: error: prototype for ‘NodeUsb::Device::Device(NodeUsb::libusb_device*)’ does not match any in class ‘NodeUsb::Device’
../src/./bindings.h:35: error: candidates are: NodeUsb::Device::Device(const NodeUsb::Device&)
../src/./bindings.h:35: error:                 NodeUsb::Device::Device()
../src/bindings.cc: In destructor ‘NodeUsb::Device::~Device()’:
../src/bindings.cc:328: error: ‘libusb_close’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::New(const v8::Arguments&)’:
../src/bindings.cc:348: error: no matching function for call to ‘NodeUsb::Device::Device(NodeUsb::libusb_device*&)’
../src/./bindings.h:35: note: candidates are: NodeUsb::Device::Device()
../src/./bindings.h:35: note:                 NodeUsb::Device::Device(const NodeUsb::Device&)
../src/bindings.cc:351: error: ‘class NodeUsb::Device’ has no member named ‘Wrap’
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::BusNumberGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/bindings.cc:363: error: ‘libusb_get_bus_number’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::DeviceAddressGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/bindings.cc:375: error: ‘libusb_get_device_address’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::Open(const v8::Arguments&)’:
../src/bindings.cc:382: error: ‘libusb_open’ was not declared in this scope
../src/bindings.cc:382: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::Close(const v8::Arguments&)’:
../src/bindings.cc:393: error: ‘libusb_close’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::GetConfigDescriptor(const v8::Arguments&)’:
../src/bindings.cc:413: error: ‘libusb_get_active_config_descriptor’ was not declared in this scope
../src/bindings.cc:413: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc:415: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:416: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:417: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:418: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:419: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:420: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:421: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:422: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:426: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:427: error: invalid use of incomplete type ‘struct NodeUsb::libusb_config_descriptor’
../src/./bindings.h:49: error: forward declaration of ‘struct NodeUsb::libusb_config_descriptor’
../src/bindings.cc:433: error: ‘libusb_free_config_descriptor’ was not declared in this scope
../src/bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodeUsb::Device::GetDeviceDescriptor(const v8::Arguments&)’:
../src/bindings.cc:444: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:444: error: ‘libusb_get_device_descriptor’ was not declared in this scope
../src/bindings.cc:444: error: ‘LIBUSB_SUCCESS’ was not declared in this scope
../src/bindings.cc:444: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:447: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:448: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:449: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:450: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:451: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:452: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:453: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:454: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:455: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:456: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:457: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:458: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:459: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
../src/bindings.cc:460: error: ‘class NodeUsb::Device’ has no member named ‘device_descriptor’
In file included from ../src/node_usb.cc:1:
../src/./bindings.h:12: error: expected class-name before ‘{’ token
../src/./bindings.h:22: error: ISO C++ forbids declaration of ‘libusb_device’ with no type
../src/./bindings.h:22: error: expected ‘;’ before ‘*’ token
../src/./bindings.h:35: error: expected class-name before ‘{’ token
../src/./bindings.h:40: error: expected `)' before ‘*’ token
../src/./bindings.h:48: error: field ‘device_descriptor’ has incomplete type
Waf: Leaving directory `/Users/pathikrit/Projects/ASD/node_modules/node-usb/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx node_usb.cc -> node_usb_1.o}
 -> task failed (err #1): 
    {task: cxx bindings.cc -> bindings_1.o}
npm ERR! node-usb@0.0.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the node-usb@0.0.1 install script.
npm ERR! This is most likely a problem with the node-usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-usb
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/pathikrit/Projects/ASD
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.30
npm ERR! code ELIFECYCLE
npm ERR! message node-usb@0.0.1 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pathikrit/Projects/ASD/npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 1
```

Can someone give me a step by step of what to do to install in either Ubuntu or Mac?

**Comment by schakko** [comment]
The NPM package is deprecated. Please use the Git repository.

**Comment by pathikrit** [comment]
I did "git clone https://github.com/schakko/node-usb.git; cd node-usb; make" and it spit out this: 

node-waf -v configure clean build; node tests/node-usb-test.js
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.18 
Checking for program pkg-config          : /usr/local/bin/pkg-config 
Checking for libusb-1.0                  : 13:34:26 runner pkg-config --errors-to-stdout --print-errors --cflags --libs libusb-1.0 
yes 
'configure' finished successfully (0.199s)
'clean' finished successfully (0.003s)
Waf: Entering directory `/Users/pathikrit/Projects/node-usb/build'
[1/6] cxx: src/node_usb.cc -> build/Release/src/node_usb_1.o
13:34:27 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/Cellar/libusb/1.0.8/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.18/include/node', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/node_usb.cc', '-c', '-o', 'Release/src/node_usb_1.o']
[2/6] cxx: src/usb.cc -> build/Release/src/usb_1.o
13:34:27 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/Cellar/libusb/1.0.8/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.18/include/node', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/usb.cc', '-c', '-o', 'Release/src/usb_1.o']
[3/6] cxx: src/device.cc -> build/Release/src/device_1.o
13:34:27 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/Cellar/libusb/1.0.8/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.18/include/node', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/device.cc', '-c', '-o', 'Release/src/device_1.o']
[4/6] cxx: src/interface.cc -> build/Release/src/interface_1.o
13:34:27 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/Cellar/libusb/1.0.8/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.18/include/node', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/interface.cc', '-c', '-o', 'Release/src/interface_1.o']
[5/6] cxx: src/endpoint.cc -> build/Release/src/endpoint_1.o
13:34:27 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/Cellar/libusb/1.0.8/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.18/include/node', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/endpoint.cc', '-c', '-o', 'Release/src/endpoint_1.o']
../src/device.cc: In static member function ‘static void NodeUsb::Device::EIO_ControlTransfer(uv_work_t*)’:
../src/device.cc:396: warning: comparison is always false due to limited range of data type
[6/6] cxx_link: build/Release/src/node_usb_1.o build/Release/src/usb_1.o build/Release/src/device_1.o build/Release/src/interface_1.o build/Release/src/endpoint_1.o -> build/Release/usb_bindings.node
13:34:27 runner system command -> ['/usr/bin/g++', 'Release/src/node_usb_1.o', 'Release/src/usb_1.o', 'Release/src/device_1.o', 'Release/src/interface_1.o', 'Release/src/endpoint_1.o', '-o', '/Users/pathikrit/Projects/node-usb/build/Release/usb_bindings.node', '-bundle', '-undefined', 'dynamic_lookup', '-L/usr/local/Cellar/libusb/1.0.8/lib', '-L/usr/local/Cellar/node/0.6.18/lib', '-lusb-1.0']
Waf: Leaving directory`/Users/pathikrit/Projects/node-usb/build'
'build' finished successfully (0.813s)
---- Failed tests does NOT mean, node-usb is working. It depends on your USB infrastructure that all tests pass. Try the examples/kinect/kinect.js for proper working
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99

assert.js:104
  throw new assert.AssertionError({
        ^
AssertionError: Device.getInterfaces() must return an array with length >= 0
    at Object.<anonymous> (/Users/pathikrit/Projects/node-usb/tests/node-usb-test.js:59:9)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
make: **\* [make] Error 1

How do I use it in my own module? I am guessing simply adding it as a dependency in package.json won't work?

**Comment by pathikrit** [comment]
I cd into the node_modules directory of my project and checkout out node-usb and make-d it. In my project, when I do require("node-usb").Usb(), I now get: Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file ../src/node_object_wrap.h, line 62.

Any idea what am I doing wrong?
