### ISSUE TITLE
Build failure on Ubuntu 12.04

### ISSUE THREAD

**Issue by pathikrit** [schakko/node-usb#14]
[redacted]$ git clone https://github.com/schakko/node-usb.git
Cloning into 'node-usb'...
remote: Counting objects: 503, done.
remote: Compressing objects: 100% (330/330), done.
remote: Total 503 (delta 319), reused 262 (delta 133)
Receiving objects: 100% (503/503), 277.15 KiB | 221 KiB/s, done.
Resolving deltas: 100% (319/319), done.
[redacted]$ cd node-usb/
[redacted]/node-usb$ node --version
v0.6.12
[redacted]/node-usb$ npm --version
1.1.4
[redacted]/node-usb$ make
node-waf -v configure clean build; node tests/node-usb-test.js
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for libusb-1.0                  : 23:06:15 runner pkg-config --errors-to-stdout --print-errors --cflags --libs libusb-1.0 
yes 
'configure' finished successfully (0.083s)
'clean' finished successfully (0.004s)
Waf: Entering directory `/home/addepar/Desktop/rick_hackery/ASD/node_modules/node-usb/build'
[1/6] cxx: src/node_usb.cc -> build/Release/src/node_usb_1.o
23:06:15 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-I/usr/include/libusb-1.0', '-I/usr/include/nodejs', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/node_usb.cc', '-c', '-o', 'Release/src/node_usb_1.o']
[2/6] cxx: src/usb.cc -> build/Release/src/usb_1.o
23:06:15 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-I/usr/include/libusb-1.0', '-I/usr/include/nodejs', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/usb.cc', '-c', '-o', 'Release/src/usb_1.o']
[3/6] cxx: src/device.cc -> build/Release/src/device_1.o
23:06:15 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-I/usr/include/libusb-1.0', '-I/usr/include/nodejs', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/device.cc', '-c', '-o', 'Release/src/device_1.o']
[4/6] cxx: src/interface.cc -> build/Release/src/interface_1.o
23:06:15 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-I/usr/include/libusb-1.0', '-I/usr/include/nodejs', '-DNODE_USB_REVISION="61986afa8d9cdf28121d29d47d28a57da0f7d853"', '../src/interface.cc', '-c', '-o', 'Release/src/interface_1.o']
In file included from ../src/bindings.h:4:0,
                 from ../src/usb.h:4,
                 from ../src/node_usb.cc:1:
../src/node_usb.h:22:27: fatal error: uv-private/ev.h: No such file or directory
compilation terminated.
In file included from ../src/bindings.h:4:0,
                 from ../src/usb.h:4,
                 from ../src/usb.cc:1:
../src/node_usb.h:22:27: fatal error: uv-private/ev.h: No such file or directory
compilation terminated.
In file included from ../src/bindings.h:4:0,
                 from ../src/interface.cc:1:
../src/node_usb.h:22:27: fatal error: uv-private/ev.h: No such file or directory
compilation terminated.
In file included from ../src/bindings.h:4:0,
                 from ../src/device.cc:1:
../src/node_usb.h:22:27: fatal error: uv-private/ev.h: No such file or directory
compilation terminated.
Waf: Leaving directory`/home/addepar/Desktop/rick_hackery/ASD/node_modules/node-usb/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx node_usb.cc -> node_usb_1.o}
 -> task failed (err #1): 
    {task: cxx usb.cc -> usb_1.o}
 -> task failed (err #1): 
    {task: cxx interface.cc -> interface_1.o}
 -> task failed (err #1): 
    {task: cxx device.cc -> device_1.o}

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module './usb_bindings'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/addepar/Desktop/rick_hackery/ASD/node_modules/node-usb/usb.js:4:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
make: **\* [make] Error 1

**Comment by mlabieniec** [comment]
I have the same issue

**Comment by pathikrit** [comment]
I managed to get around it by using a different node-usb (see my [package.json](https://github.com/pathikrit/node-thunder-driver/blob/master/package.json))
