### ISSUE TITLE
 Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by bharrell-rsc** [schakko/node-usb#18]
I'm trying to use node-usb in an appjs app (node.exe v0.8.21). I got libusbx and node-usb built/installed, and my app runs fine until i add "var usb = require('usb')" to the top. Now when i run the app i get:

C:\Users\bharrell\Desktop\test\app\data>.\bin\node.exe --harmony .\app.js

C:\Users\bharrell\Desktop\test\app\data\node_modules\usb\node_modules\bindings\bindings.js:79
        throw e
              ^
Error: The specified procedure could not be found.
C:\Users\bharrell\Desktop\test\app\data\node_modules\usb\build\Release\usb_bindings.node
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (C:\Users\bharrell\Desktop\test\app\data\node_modules\usb\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (C:\Users\bharrell\Desktop\test\app\data\node_modules\usb\usb.js:1:119)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

**Comment by bharrell-rsc** [comment]
Well I feel silly! I was building with node 0.10.x installed on my machine, but running it in appjs which uses(comes packaged with) node 0.8.x. I uninstalled 0.10, installed 0.8, rebuilt with that, and it runs fine. Make sure you build modules with the same version of node that you're going to run them on!
